template_project/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url('^$', views.index, name='index'),
    url('^other/', views.other, name='other'),
    url('^relative/', views.relative, name='relative'),
]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('other/', include('basic_app.urls')),
    path('relative/', include('basic_app.urls')),
]

template_project/basic_app/models.py
from django.db import models

# Create your models here.

template_project/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    my_dict = {'text' : "Hello World", 'num':100 }
    return render(request, 'basic_app/index.html', context=my_dict)


def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

template_project/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar brand" href="{% url 'basic_app:index' %}">Brand</a></li>
          <li><a class="navbar link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited, if you will extend -->
      {% endblock %}
    </div>
  </body>
</html>

template_project/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load custom_tags %}

  {% block body_block %}
    <h1>Welcome to Index Page</h1>
    <h1>{{ text | cuttt:'World' }}</h1>
    <h1>{{ num | add:'100' }}</h1>
  {% endblock %}

template_project/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block%}
    <h1>Welcome to Other Html page</h1>
    <h1>This is an example of template inheritance</h1>
  {% endblock %}

template_project/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to relative url template page</h1>
  {% endblock %}